// src/core/utils/stories/pythagoras.stories.ts
import { StoryScenario } from '../WordProblemInterceptor.js';

export const PYTHAGORAS_STORIES: Record<string, StoryScenario[]> = {
    // =========================================================================
    // 🔺 1. PYTH HYPOTENUSE (15 Stories) - Parameters: {a}, {b}, {c}
    // =========================================================================
    pyth_hypotenuse: [
        { sv: "En skateboardramp är {a} dm lång på marken och {b} dm hög i bakre kanten. Hur lång är själva åkytan?", en: "A skateboard ramp is {a} dm long on the ground and {b} dm high at the back. How long is the riding surface?" },
        { sv: "Du fäster en ljusslinga från golvet upp till toppen av en vägg. Slingan går {a} m längs golvet och väggen är {b} m hög. Hur lång är ljusslingan?", en: "You attach a string light from the floor to the top of a wall. The string goes {a} m along the floor and the wall is {b} m high. How long is the string light?" },
        { sv: "En bit dekorationsband spänns diagonalt över en kvadratisk kudde. Kuddens sidor mäter {a} cm och {b} cm. Hur långt är bandet?", en: "A decorative ribbon is stretched diagonally across a square pillow. The pillow sides measure {a} cm and {b} cm. How long is the ribbon?" },
        { sv: "Du bygger en stötta till en hylla. Stöttan ska gå från en punkt {a} cm ut på hyllan till {b} cm ner på väggen. Hur lång måste stöttan vara?", en: "You build a brace for a shelf. The brace goes from a point {a} cm out on the shelf to {b} cm down the wall. How long must the brace be?" },
        { sv: "En tältlina är spänd från marken till toppen av en tältpinne. Avståndet på marken är {a} dm och pinnen är {b} dm hög. Hur lång är linan?", en: "A tent wire is stretched from the ground to the top of a pole. The ground distance is {a} dm and the pole is {b} dm high. How long is the wire?" },
        { sv: "Du klipper ut en rätvinklig tygbit till en hoodie-ficka. De två korta sidorna är {a} cm och {b} cm. Hur lång är den längsta sneda sidan?", en: "You cut a right-angled piece of fabric for a hoodie pocket. The two short sides are {a} cm and {b} cm. How long is the longest slanted edge?" },
        { sv: "En mobilskärm har bredden {a} cm och höjden {b} cm. Bestäm skärmens diagonala mått.", en: "A phone screen has a width of {a} cm and a height of {b} cm. Determine the screen's diagonal measure." },
        { sv: "Du går {a} meter rakt österut på skolgården och svänger sedan {b} meter rakt norrut. Hur långt är det fågelvägen tillbaka till din startpunkt?", en: "You walk {a} meters due east on the schoolyard and then turn {b} meters due north. How far is it in a straight line back to your starting point?" },
        { sv: "En bärbar dator har en bas på {a} cm och en skärmhöjd på {b} cm när den är öppen i rät vinkel. Hur långt är det från basens framkant till skärmens överkant?", en: "A laptop has a base of {a} cm and a screen height of {b} cm when open at a right angle. How far is it from the front of the base to the top of the screen?" },
        { sv: "Du ritar en rätvinklig triangel i ett grafikprogram. De två kateterna mäter {a} mm och {b} mm. Hur lång blir hypotenusan?", en: "You draw a right triangle in a graphics app. The two legs measure {a} mm and {b} mm. How long will the hypotenuse be?" },
        { sv: "En vikbar led-lampa står på ett bord. Basen är {a} cm och armen sträcker sig {b} cm spikrakt uppåt. Vad är avståndet diagonalt mellan lampans fot och topp?", en: "A folding LED lamp stands on a table. The base is {a} cm and the arm extends {b} cm straight up. What is the diagonal distance between the lamp's base and top?" },
        { sv: "En rektangulär datormusmatta mäter {a} cm gånger {b} cm. Hur lång blir en linje dragen från ett hörn till det motsatta hörnet?", en: "A rectangular computer mousepad measures {a} cm by {b} cm. How long will a line drawn from one corner to the opposite corner be?" },
        { sv: "Ett litet segel till en modellbåt har en rät vinkel längst ner. Bottenkanten är {a} cm och den vertikala kanten är {b} cm. Hur lång är den sneda kanten?", en: "A small sail for a model boat has a right angle at the bottom. The bottom edge is {a} cm and the vertical edge is {b} cm. How long is the slanted edge?" },
        { sv: "Du placerar en router {a} dm från en vägg och drar en nätverkskabel diagonalt upp till ett uttag på väggen som sitter {b} dm högt. Hur lång sladd behövs?", en: "You place a router {a} dm from a wall and run a network cable diagonally up to a wall socket that is {b} dm high. How long a cable is needed?" },
        { sv: "En kvadratisk rörbit i ett staket kapas snett. Snittet går {a} mm djupt och {b} mm brett. Hur långt blir själva snittet?", en: "A square pipe section in a fence is cut at an angle. The cut runs {a} mm deep and {b} mm wide. How long will the cut itself be?" }
    ],

    // =========================================================================
    // 🔺 2. PYTH LEG (15 Stories) - Parameters: {a} (known leg), {b} (missing leg), {c} (hypotenuse)
    // =========================================================================
    pyth_leg: [
        { sv: "En {c} meter lång stege lutar mot en vägg. Stegens fot står {a} meter ut på marken från väggen. Hur högt upp når stegen?", en: "A {c} meter long ladder leans against a wall. The foot of the ladder is {a} meters out on the ground from the wall. How high up does the ladder reach?" },
        { sv: "En sned lina på {c} dm håller uppe en hylla. Linan är fäst {a} dm ut på hyllplanet. Hur långt ner på väggen är linans andra ände fäst?", en: "A slanted cord of {c} dm holds up a shelf. The cord is attached {a} dm out on the shelf. How far down the wall is the other end of the cord attached?" },
        { sv: "En bildskärm har diagonalen {c} cm och bredden {a} cm. Beräkna bildskärmens höjd.", en: "A monitor screen has a diagonal of {c} cm and a width of {a} cm. Calculate the height of the screen." },
        { sv: "Du spänner en lina diagonalt i en rektangulär ram för att stabilisera den. Linan är {c} cm lång och ramens botten är {a} cm bred. Hur hög är ramen?", en: "You stretch a wire diagonally across a rectangular frame to stabilize it. The wire is {c} cm long and the bottom of the frame is {a} cm wide. How high is the frame?" },
        { sv: "En rätvinklig skateboardramp har en åkyta på {c} dm. Längs marken mäter rampen {a} dm. Hur hög är rampen i sin bakre kant?", en: "A right-angled skateboard ramp has a riding surface of {c} dm. Along the ground, the ramp measures {a} dm. How high is the ramp at its back edge?" },
        { sv: "En tältlina är {c} dm lång. Den är fäst i marken {a} dm från tältets vertikala mittstång. Hur högt upp på stången sitter linan fäst?", en: "A tent wire is {c} dm long. It is fixed to the ground {a} dm from the vertical center pole. How high up the pole is the wire attached?" },
        { sv: "Fågelvägen mellan ditt hus och gymmet är {c} meter. Om du först måste gå {a} meter rakt österut för att sedan svänga rakt norrut, hur lång är den sista norrgående sträckan?", en: "The straight-line distance between your house and the gym is {c} meters. If you must first walk {a} meters due east and then turn due north, how long is that last northbound segment?" },
        { sv: "Ett snedställt stag i en cykelram är {c} cm långt. Det horisontella röret är {a} cm brett. Bestäm det vertikala rörets höjd.", en: "A slanted stay in a bicycle frame is {c} cm long. The horizontal tube is {a} cm wide. Determine the height of the vertical tube." },
        { sv: "En rektangulär profilbild har diagonalen {c} mm och bredden {a} mm. Hur hög är profilbilden i millimeter?", en: "A rectangular profile picture has a diagonal of {c} mm and a width of {a} mm. How tall is the profile picture in millimeters?" },
        { sv: "Ett segel till en modellbåt har en sned kant på {c} cm. Bottenkanten mäter {a} cm. Hur hög är seglets vertikala mastkant?", en: "A sail for a model boat has a slanted edge of {c} cm. The bottom edge measures {a} cm. How tall is the sail's vertical mast edge?" },
        { sv: "En led-arm till en skrivbordslampa mäter {c} cm. När den är vinklad sträcker den sig {a} cm ut över bordet i sidled. På vilken höjd hamnar lampans topp?", en: "A desk lamp arm measures {c} cm. When angled, it extends {a} cm horizontally over the table. At what height does the top of the lamp end up?" },
        { sv: "En nätverkskabel på {c} dm spänns diagonalt från en router på golvet till ett vägguttag. Routern står {a} dm från väggen. Hur högt upp sitter uttaget?", en: "A network cable of {c} dm is stretched diagonally from a router on the floor to a wall socket. The router is {a} dm from the wall. How high up is the socket?" },
        { sv: "En rektangulär musmatta har en diagonal på {c} cm. Musmattans långsida mäter {a} cm. Hur bred är musmattans kortsida?", en: "A rectangular mousepad has a diagonal of {c} cm. The long side of the mousepad measures {a} cm. How wide is the short side?" },
        { sv: "Du bygger en träram till ett konstprojekt. Den diagonala stödlisten är {c} cm lång och ramens höjd är {a} cm. Hur bred är ramens botten?", en: "You build a wooden frame for an art project. The diagonal support piece is {c} cm long and the height of the frame is {a} cm. How wide is the frame's bottom?" },
        { sv: "En snett kapad metallbit har en sned snittyta på {c} mm. Snittets djup i metallen är {a} mm. Hur brett sträcker sig snittet?", en: "An angled piece of metal has a slanted cut edge of {c} mm. The depth of the cut into the metal is {a} mm. How wide does the cut extend?" }
    ],

    // =========================================================================
    // 🔺 3. PYTH DIAGONAL (15 Stories) - Parameters: {a}, {b}, {c}
    // =========================================================================
    pyth_diagonal: [
        { sv: "Ett rektangulärt gamingrum mäter {a} meter på ena väggen och {b} meter på den andra. Hur långt är det diagonalt tvärs över rummet?", en: "A rectangular gaming room measures {a} meters on one wall and {b} meters on the other. How far is it diagonally across the room?" },
        { sv: "En rektangulär skolgård har sidorna {a} m och {b} m. Du genar diagonalt från ett hörn till det motsatta hörnet. Hur långt springer du?", en: "A rectangular schoolyard has sides of {a} m and {b} m. You shortcut diagonally from one corner to the opposite corner. How far do you run?" },
        { sv: "Du ska skicka en affisch i en platt rektangulär kartong som mäter {a} cm gånger {b} cm. Hur lång är kartongens diagonal?", en: "You are shipping a poster in a flat rectangular box measuring {a} cm by {b} cm. How long is the box's diagonal?" },
        { sv: "En surfplatta har skärmmåtten {a} cm och {b} cm. Hur lång blir skärmens diagonal i centimeter?", en: "A tablet screen has dimensions of {a} cm and {b} cm. How long is the screen's diagonal in centimeters?" },
        { sv: "En rektangulär fotbollsplan mäter {a} meter på längden och {b} meter på bredden. Hur långt är det mellan två motsatta hörn?", en: "A rectangular football field measures {a} meters in length and {b} meters in width. How far is it between two opposite corners?" },
        { sv: "En TV-bänk har en rektangulär baksida som mäter {a} cm i bredd och {b} cm i höjd. Hur lång blir en dekorationslinje från hörn till hörn?", en: "A TV stand has a rectangular back that measures {a} cm in width and {b} cm in height. How long will a decorative corner-to-corner line be?" },
        { sv: "En bit digital grafik ritas som en rektangel med måtten {a} px och {b} px. Hur lång blir diagonalen i pixlar?", en: "A piece of digital graphic is drawn as a rectangle measuring {a} px by {b} px. How long is the diagonal in pixels?" },
        { sv: "Ett kvadratiskt eller rektangulärt fönster har måtten {a} dm och {b} dm. Hur lång är glasrutans diagonal?", en: "A window pane has dimensions of {a} dm and {b} dm. How long is the diagonal of the glass?" },
        { sv: "En bit designtyg till en hoodie-logga klipps rektangulärt med måtten {a} cm och {b} cm. Bestäm diagonalens längd.", en: "A piece of fabric for a hoodie logo is cut into a rectangle measuring {a} cm by {b} cm. Determine the length of the diagonal." },
        { sv: "Du bygger en rektangulär skateboard-låda som mäter {a} dm på längden och {b} dm på bredden. Hur långt är det mellan de yttre hörnen diagonalt?", en: "You build a rectangular skateboard box measuring {a} dm in length and {b} dm in width. How long is it between the outer corners diagonally?" },
        { sv: "Ett rektangulärt klistermärke på din bärbara dator mäter {a} mm gånger {b} mm. Hur lång är dess diagonal?", en: "A rectangular sticker on your laptop measures {a} mm by {b} mm. How long is its diagonal?" },
        { sv: "En rektangulär biolokal har måtten {a} m och {b} m. Hur långt är avståndet diagonalt från projektorn till dukens motsatta sida?", en: "A rectangular cinema room has dimensions of {a} m and {b} m. How long is the diagonal distance across the room?" },
        { sv: "En skiss över ett rum visar en rektangulär säng på {a} cm gånger {b} cm. Vad mäter sängens diagonal på ritningen?", en: "A layout sketch shows a rectangular bed measuring {a} cm by {b} cm. What does the bed's diagonal measure on the drawing?" },
        { sv: "Ett rektangulärt kretskort i en kontroll mäter {a} mm på kortsidan och {b} mm på långsidan. Hur lång är kretskortets diagonal?", en: "A rectangular circuit board in a controller measures {a} mm on the short side and {b} mm on the long side. How long is the board's diagonal?" },
        { sv: "Ett rektangulärt matbord har sidorna {a} cm och {b} cm. Hur lång blir en löpare som läggs spikrakt diagonalt över bordet?", en: "A rectangular dining table has sides of {a} cm and {b} cm. How long will a table runner laid straight diagonally across the table be?" }
    ]
};