// src/core/utils/stories/similarity.stories.ts
import { StoryScenario } from '../WordProblemInterceptor.js';

export const SIMILARITY_STORIES: Record<string, StoryScenario[]> = {
    // =========================================================================
    // 📐 1. SIMILARITY: CALCULATE BIG SIDE (15 Stories)
    //    Parameters: {s1} (small base), {s2} (small height), {bigS2} (large height) -> Find bigS1 ('x')
    // =========================================================================
    similarity_calc_big: [
        { sv: "En liten bild på en mobilskärm är {s1} cm bred och {s2} cm hög. Bilden förstoras upp på en TV så att höjden blir {bigS2} cm. Hur bred blir bilden på TV-skärmen?", en: "A small picture on a phone screen is {s1} cm wide and {s2} cm tall. The picture is blown up on a TV so the height becomes {bigS2} cm. How wide will the picture be on the TV?" },
        { sv: "Ett litet klistermärke har bredden {s1} cm och höjden {s2} cm. Samma bild trycks på en stor affisch som görs med höjden {bigS2} cm. Hur bred blir affischen?", en: "A small sticker has a width of {s1} cm and a height of {s2} cm. The same image is printed on a large poster made with a height of {bigS2} cm. How wide will the poster be?" },
        { sv: "En liten chokladkaka mäter {s1} cm i botten och {s2} cm på höjden. En jättestor likformig chokladkaka i en godisaffär görs med höjden {bigS2} cm. Hur bred är den stora chokladkakan i botten?", en: "A small chocolate bar measures {s1} cm at the bottom and {s2} cm in height. A giant similar chocolate bar in a candy shop is made with a height of {bigS2} cm. How wide is the big chocolate bar at the bottom?" },
        { sv: "En liten profilbild i en app är {s1} pixlar lång och {s2} pixlar bred. Den visas större på en surfplatta där bredden blir {bigS2} pixlar. Hur lång blir profilbilden på surfplattan?", en: "A small profile picture in an app is {s1} pixels long and {s2} pixels wide. It is shown larger on a tablet where the width becomes {bigS2} pixels. How long will the profile picture be on the tablet?" },
        { sv: "En bild på en hoodie visar en logga som är {s1} cm bred och {s2} cm hög. På en stor reklamskylt på stan görs samma logga med höjden {bigS2} cm. Hur bred blir loggan på skylten?", en: "A picture on a hoodie shows a logo that is {s1} cm wide and {s2} cm tall. On a big street billboard, the same logo is made with a height of {bigS2} cm. How wide will the logo be on the billboard?" },
        { sv: "Ett litet spelkort är {s1} cm brett och {s2} cm långt. En stor likformig samlarbox har längden {bigS2} cm. Vad blir boxens bredd?", en: "A small gaming card is {s1} cm wide and {s2} cm long. A large similar collector's box has a length of {bigS2} cm. What will the box's width be?" },
        { sv: "Ett litet musmatta-prov är {s1} cm brett och {s2} cm långt. Den riktiga stora musmattan görs likformig med längden {bigS2} cm. Hur bred blir den riktiga musmattan?", en: "A small mousepad sample is {s1} cm wide and {s2} cm long. The real big mousepad is made similar with a length of {bigS2} cm. How wide will the real mousepad be?" },
        { sv: "Ett litet tryck på en keps har basen {s1} mm och höjden {s2} mm. Samma tryck görs på en t-shirt där höjden blir {bigS2} mm. Hur brett blir trycket på t-shirten?", en: "A small print on a cap has a base of {s1} mm and a height of {s2} mm. The same print is made on a t-shirt where the height becomes {bigS2} mm. How wide will the print be on the t-shirt?" },
        { sv: "Ett litet foto har måtten {s1} cm gånger {s2} cm. Fotot visas på en stor datorskärm där höjden blir {bigS2} cm. Vad blir fotots bredd på datorskärmen?", en: "A small photo measures {s1} cm by {s2} cm. The photo is shown on a large computer screen where the height becomes {bigS2} cm. What will the photo's width be on the computer screen?" },
        { sv: "Ett litet serietidningsomslag är {s1} cm brett och {s2} cm högt på en dataskiss. I verkligheten trycks tidningen med höjden {bigS2} cm. Hur brett blir det riktiga omslaget?", en: "A small comic book cover is {s1} cm wide and {s2} cm tall on a computer draft. In reality, the comic book is printed with a height of {bigS2} cm. How wide will the real cover be?" },
        { sv: "Ett litet pappersflygplan har måtten {s1} cm och {s2} cm. Ett stort likformigt flygplan i kartong byggs till ett skolprojekt där höjden blir {bigS2} cm. Bestäm det stora kartongflygplanets bredd.", en: "A small paper airplane measures {s1} cm and {s2} cm. A large similar cardboard airplane is built for a school project where the height becomes {bigS2} cm. Determine the large cardboard airplane's width." },
        { sv: "Framsidan på ett tv-spel är {s1} cm bred och {s2} cm hög. En stor reklamaffisch för spelet trycks med höjden {bigS2} cm. Hur bred blir reklamaffischen?", en: "The front cover of a video game is {s1} cm wide and {s2} cm tall. A big advertising poster for the game is printed with a height of {bigS2} cm. How wide will the poster be?" },
        { sv: "En liten bit av en datorskrift mäter {s1} mm i basen och {s2} mm i höjden. När man zoomar in på skärmen blir höjden {bigS2} mm. Vad mäter basen när man har zoomat in?", en: "A small piece of a computer font measures {s1} mm at the base and {s2} mm in height. When zoomed in on the screen, the height becomes {bigS2} mm. What does the base measure when zoomed in?" },
        { sv: "En skiss av en rektangulär skateboard-pool har måtten {s1} cm och {s2} cm. I verkligheten byggs poolen så att den långa sidan blir {bigS2} m. Hur bred blir den riktiga poolen?", en: "A sketch of a rectangular skateboard pool has dimensions of {s1} cm and {s2} cm. In reality, the pool is built so that the long side is {bigS2} m. How wide will the real pool be?" },
        { sv: "En liten ikon på mobilen har bredden {s1} mm och höjden {s2} mm. Samma ikon görs likformig på en datorskärm så att dess höjd blir {bigS2} mm. Bestäm ikonens bredd på datorskärmen.", en: "A small icon on a phone has a width of {s1} mm and a height of {s2} mm. The same icon is made similar on a computer monitor so its height becomes {bigS2} mm. Determine the icon's width on the computer monitor." }
    ],

    // =========================================================================
    // 📐 2. SIMILARITY: CALCULATE SMALL SIDE (15 Stories)
    //    Parameters: {bigS1} (large base), {bigS2} (large height), {s2} (small height) -> Find s1 ('x')
    // =========================================================================
    similarity_calc_small: [
        { sv: "En stor bioskärm är {bigS1} m bred och {bigS2} m hög. En liten likformig datorskärm har höjden {s2} cm. Bestäm den lilla datorskärmens bredd.", en: "A large cinema screen is {bigS1} m wide and {bigS2} m tall. A small similar computer screen has a height of {s2} cm. Determine the small computer screen's width." },
        { sv: "En fotbollsplan är {bigS1} m lång och {bigS2} m bred. I ett tv-spel ritas en likformig minivariant av planen med bredden {s2} cm. Hur lång blir planen i tv-spelet?", en: "A football field is {bigS1} m long and {bigS2} m wide. In a video game, a similar mini-version of the field is drawn with a width of {s2} cm. How long will the field be in the video game?" },
        { sv: "En stor flagga på ett hus är {bigS1} cm lång och {bigS2} cm bred. En liten likformig miniflagga görs med bredden {s2} cm. Hur lång blir miniflaggan?", en: "A large flag on a building is {bigS1} cm long and {bigS2} cm wide. A small similar mini-flag is made with a width of {s2} cm. How long will the mini-flag be?" },
        { sv: "En stor väggmålning är {bigS1} cm bred och {bigS2} cm hög. I ett litet anteckningsblock är bilden likformig med höjden {s2} cm. Hur bred är bilden i blocket?", en: "A large mural is {bigS1} cm wide and {bigS2} cm high. In a small notebook, the image is similar with a height of {s2} cm. How wide is the image in the notebook?" },
        { sv: "En riktig skateboard-ramp är {bigS1} dm lång och {bigS2} dm hög. En leksaksramp för fingerboards tillverkas helt likformig med höjden {s2} cm. Hur lång blir leksaksrampen?", en: "A real skateboard ramp is {bigS1} dm long and {bigS2} dm high. A toy ramp for fingerboards is manufactured completely similar with a height of {s2} cm. How long will the toy ramp be?" },
        { sv: "Ett stort fönster har måtten {bigS1} cm och {bigS2} cm. På en liten teckning ritas fönstret likformigt med höjden {s2} mm. Vad blir dess bredd på teckningen?", en: "A large window has dimensions of {bigS1} cm and {bigS2} cm. On a small drawing, the window is drawn similarly with a height of {s2} mm. What will its width be on the drawing?" },
        { sv: "En stor tv-skärm har bredden {bigS1} mm och höjden {bigS2} mm. En liten bild på skärmen visar en likformig miniskärm med höjden {s2} pixlar. Bestäm minibildens bredd.", en: "A large TV screen has a width of {bigS1} mm and a height of {bigS2} mm. A small image on the screen shows a similar mini-screen with a height of {s2} pixels. Determine the mini-image's width." },
        { sv: "En stor skolgård mäter {bigS1} m gånger {bigS2} m. På en liten skiss över skolan är gården likformigt inritad med höjden {s2} cm. Hur bred blir skolgården på skissen?", en: "A large schoolyard measures {bigS1} m by {bigS2} m. On a small sketch of the school, the yard is drawn similarly with a height of {s2} cm. How wide will the schoolyard be on the sketch?" },
        { sv: "En stor reklamskylt är {bigS1} cm bred och {bigS2} cm hög. En liten bild i en reklamfolder görs likformig med höjden {s2} mm. Hur bred är bilden i foldern?", en: "A large billboard is {bigS1} cm wide and {bigS2} cm high. A small picture in a flyer is made similar with a height of {s2} mm. How wide is the picture in the flyer?" },
        { sv: "En stor segelbåt har ett segel med basen {bigS1} m och höjden {bigS2} m. En leksaksbåt har ett likformigt segel med höjden {s2} cm. Bestäm leksaksseglets bas.", en: "A large sailboat has a sail with a base of {bigS1} m and a height of {bigS2} m. A toy boat has a similar sail with a height of {s2} cm. Determine the toy sail's base." },
        { sv: "En stor scen på en konsert är {bigS1} cm lång och {bigS2} cm hög. På en liten skiss har scenen gjorts likformig med höjden {s2} mm. Hur lång är scenen på skissen?", en: "A large concert stage is {bigS1} cm long and {bigS2} cm high. On a small sketch, the stage is made similar with a height of {s2} mm. How long is the stage on the sketch?" },
        { sv: "En rektangulär matta mäter {bigS1} m i längd och {bigS2} m i bredd. I en produktkatalog avbildas mattan likformigt med bredden {s2} cm. Bestäm mattans längd i katalogen.", en: "A rectangular rug measures {bigS1} m in length and {bigS2} m in width. In a product catalog, the rug is depicted similarly with a width of {s2} cm. Determine the rug's length in the catalog." },
        { sv: "En stor surfplatta mäter {bigS1} mm i bredd och {bigS2} mm i höjd. En liten bild i instruktionsboken ritas likformigt med höjden {s2} mm. Hur bred blir bilden i boken?", en: "A large tablet measures {bigS1} mm in width and {bigS2} mm in height. A small picture in the manual is drawn similarly with a height of {s2} mm. How wide will the picture in the manual be?" },
        { sv: "En stor rektangulär affisch mäter {bigS1} cm och {bigS2} cm längs kanterna. På en liten bild på mobilen visas affischen likformigt med den korta sidan som {s2} cm. Bestäm den längre sidans mått på mobilen.", en: "A large rectangular poster measures {bigS1} cm and {bigS2} cm along its edges. On a small phone image, the poster is shown similarly with the shorter side as {s2} cm. Determine the longer side's measure on the phone." },
        { sv: "En riktig flygplansvinge har måtten {bigS1} cm och {bigS2} cm. En liten leksaksmodell byggs likformig med höjden {s2} cm. Hur bred blir leksaksvingen?", en: "A real airplane wing has dimensions of {bigS1} cm and {bigS2} cm. A small toy model is built similar with a height of {s2} cm. How wide will the toy wing be?" }
    ],

    // =========================================================================
    // 📐 3. SIMILARITY: FIND SCALE FACTOR K (15 Stories)
    //    Parameters: {s1}, {s2}, {bigS1}, {bigS2} -> Find k
    // =========================================================================
    similarity_find_k: [
        { sv: "En liten kartong har basen {s1} cm och höjden {s2} cm. En stor flyttlåda är likformig med måtten {bigS1} cm och {bigS2} cm. Bestäm skalfaktorn mellan lådorna.", en: "A small cardboard box has a base of {s1} cm and a height of {s2} cm. A large moving box is similar with dimensions {bigS1} cm and {bigS2} cm. Determine the scale factor between the boxes." },
        { sv: "En liten logga på en hemsida mäter {s1} mm gånger {s2} mm. På en stor plansch har loggan förstorats likformigt till {bigS1} mm gånger {bigS2} mm. Vilken skalfaktor användes?", en: "A small logo on a website measures {s1} mm by {s2} mm. On a large poster, the logo is magnified similarly to {bigS1} mm by {bigS2} mm. What scale factor was applied?" },
        { sv: "En konstnär ritar en liten bild med bredden {s1} cm och höjden {s2} cm. Den färdiga likformiga målningen på en vägg får måtten {bigS1} cm och {bigS2} cm. Beräkna skalfaktorn.", en: "An artist draws a small picture with a width of {s1} cm and a height of {s2} cm. The finished similar painting on a wall measures {bigS1} cm and {bigS2} cm. Calculate the scale factor." },
        { sv: "Ett litet klistermärke mäter {s1} cm i bredd och {s2} cm i höjd. En stor affisch trycks helt likformig med bredden {bigS1} cm och höjden {bigS2} cm. Vad är skalfaktorn?", en: "A small sticker measures {s1} cm in width and {s2} cm in height. A large poster is made completely similar with dimensions {bigS1} cm and {bigS2} cm. What is the scale factor?" },
        { sv: "En insekt är {s1} mm bred och {s2} mm lång. På en bild i en biologibok visas insekten likformigt förstorad till {bigS1} mm gånger {bigS2} mm. Bestäm skalfaktorn.", en: "An insect is {s1} mm wide and {s2} mm long. On a picture in a textbook, the insect is shown similarly enlarged to {bigS1} mm by {bigS2} mm. Determine the scale factor." },
        { sv: "En liten datorskiss av en skylt har måtten {s1} cm och {s2} cm. Den riktiga skylten på väggen är likformig och har måtten {bigS1} cm och {bigS2} cm. Vilken skalfaktor har använts?", en: "A small computer sketch of a sign measures {s1} cm and {s2} cm. The real sign on the wall is similar and has dimensions {bigS1} cm and {bigS2} cm. What scale factor was used?" },
        { sv: "Ett litet papper mäter {s1} cm gånger {s2} cm. Det förstoras i en kopiator till ett stort ark med måtten {bigS1} cm gånger {bigS2} cm. Räkna ut skalfaktorn.", en: "A small paper sheet measures {s1} cm by {s2} cm. It is enlarged in a copier to a large sheet with dimensions {bigS1} cm by {bigS2} cm. Calculate the scale factor." },
        { sv: "En liten ritning av en mobiltelefon har måtten {s1} mm och {s2} mm. Den riktiga telefonen tillverkas likformig med måtten {bigS1} mm och {bigS2} mm. Bestäm skalan.", en: "A small drawing of a phone has dimensions of {s1} mm and {s2} mm. The real phone is built similar with dimensions {bigS1} mm and {bigS2} mm. Determine the scale factor." },
        { sv: "En liten leksaksfigur har basmåtten {s1} cm och {s2} cm. En stor staty görs likformig med basmåtten {bigS1} cm och {bigS2} cm. Vad är skalfaktorn från leksaken till statyn?", en: "A small toy figure has base dimensions of {s1} cm and {s2} cm. A large statue is made similar with base dimensions {bigS1} cm and {bigS2} cm. What is the scale factor from the toy to the statue?" },
        { sv: "Ett foto som mäter {s1} cm i bredd och {s2} cm i höjd visas på en projektor. På väggen blir bilden likformig med måtten {bigS1} cm och {bigS2} cm. Bestäm skalfaktorn.", en: "A photo measuring {s1} cm in width and {s2} cm in height is shown on a projector. On the wall, the image is similar with dimensions {bigS1} cm and {bigS2} cm. Determine the scale factor." },
        { sv: "En liten spelikons knapp mäter {s1} pixlar och {s2} pixlar. Den förstoras på skärmen till en stor knapp med måtten {bigS1} pixlar och {bigS2} pixlar. Vilken skalfaktor användes?", en: "A small game icon button measures {s1} pixels and {s2} pixels. It is enlarged on the screen to a large button with dimensions {bigS1} pixels and {bigS2} pixels. What scale factor was used?" },
        { sv: "En skiss av en tavelram anger måtten {s1} mm och {s2} mm. Den riktiga träramen tillverkas helt likformig med måtten {bigS1} mm och {bigS2} mm. Beräkna ramens skalfaktor.", en: "A sketch of a picture frame specifies dimensions of {s1} mm and {s2} mm. The real wooden frame is made completely similar with dimensions {bigS1} mm and {bigS2} mm. Calculate the frame's scale factor." },
        { sv: "Ett mönster på en datorskärm har måtten {s1} cm och {s2} cm. Mönstret förstoras upp på en gardin till {bigS1} cm och {bigS2} cm. Bestäm skalfaktorn.", en: "A pattern on a computer screen has dimensions of {s1} cm and {s2} cm. The pattern is scaled up on a curtain to {bigS1} cm and {bigS2} cm. Determine the scale factor." },
        { sv: "En digital bild mäter {s1} mm i basen och {s2} mm i höjden. Bilden skalas om likformigt i ett redigeringsprogram till {bigS1} mm och {bigS2} mm. Bestäm skalfaktorn.", en: "A digital image measures {s1} mm at the base and {s2} mm in height. The image is rescaled similarly in an editor to {bigS1} mm and {bigS2} mm. Determine the scale factor." },
        { sv: "En liten kakelplatta har måtten {s1} cm och {s2} cm. En stor likformig bordsskiva tillverkas med måtten {bigS1} cm och {bigS2} cm. Vad är skalfaktorn från plattan till skivan?", en: "A small tile measures {s1} cm and {s2} cm. A large similar tabletop is manufactured with dimensions {bigS1} cm and {bigS2} cm. What is the scale factor from the tile to the tabletop?" }
    ],

    // =========================================================================
    // 📐 4. TRANSVERSAL: TOTAL SIDE VIEW (15 Stories)
    //    Parameters: {top}, {extra}, {smallBase}, {totSide} -> Find bigBase ('x')
    // =========================================================================
    transversal_total: [
        { sv: "En liten triangelformad bit av ett skateboard-hopp har sidolängden {top} dm och en platt botten på {smallBase} dm. Hela hoppet byggs ut likformigt i samma vinkel så att hela sidolängden blir {totSide} dm. Hur lång blir hela den nya botten?", en: "A small triangular section of a skateboard ramp has a side length of {top} dm and a flat bottom of {smallBase} dm. The whole ramp is expanded similarly at the same angle so the total side length reaches {totSide} dm. How long will the entire new bottom be?" },
        { sv: "Ett litet triangelformat segel på en leksaksbåt har sidolängden {top} m och en bredd nertill på {smallBase} m. Ett större segel sys likformigt över det så att den totala yttre sidolängden blir {totSide} m. Beräkna det stora seglets bredd nertill.", en: "A small triangular sail on a toy boat has a side length of {top} m and a width at the bottom of {smallBase} m. A larger sail is made similarly over it so the total outer side length becomes {totSide} m. Calculate the large sail's width at the bottom." },
        { sv: "I en liten teckning bildar ett takstöd en triangel med sidolängden {top} mm och bredden {smallBase} mm. Det riktiga stödet utanför bildar en likformig triangel med en total sidolängd på {totSide} mm. Hur lång är den stora basen på det riktiga stödet?", en: "In a small drawing, a roof support forms a triangle with a side length of {top} mm and a width of {smallBase} mm. The real support outside forms a similar triangle with a total side length of {totSide} mm. How long is the big base on the real support?" },
        { sv: "En triangel på en tröja har överkanten {top} cm och basen {smallBase} cm. Den byggs ut likformigt till ett större mönster där hela sidolängden blir {totSide} cm. Vad mäter den nya stora basen?", en: "A triangle on a sweatshirt has an upper edge of {top} cm and a base of {smallBase} cm. It is expanded similarly into a larger pattern where the total side length becomes {totSide} cm. What does the new large base measure?" },
        { sv: "En liten modell av ett triangelformat tält har sidolängden {top} cm och basen {smallBase} cm. Det riktiga tältet byggs likformigt med en total sidolängd på {totSide} dm. Hur bred blir tältets golvbas?", en: "A small model of a triangular tent has a side length of {top} cm and a base of {smallBase} cm. The real tent is built similar with a total side length of {totSide} dm. How wide will the tent floor base be?" },
        { sv: "Ett mönster till ett fönster innehåller en inre triangel med sidolängden {top} mm och basen {smallBase} mm. Den yttre ramen bildar en likformig triangel med sidolängden {totSide} mm. Beräkna ramens bas.", en: "A pattern for a window contains an inner triangle with a side length of {top} mm and a base of {smallBase} mm. The outer frame forms a similar triangle with a side length of {totSide} mm. Calculate the frame's base." },
        { sv: "Ett litet hyllstöd har sidolängden {top} cm and basen {smallBase} cm. Ett större och starkare stöd monteras likformigt över det med den totala sidolängden {totSide} cm. Bestäm det stora stödets bas.", en: "A small shelf bracket has a side length of {top} cm and a base of {smallBase} cm. A larger reinforced bracket is mounted over it with a total side length of {totSide} cm. Determine the large bracket's base." },
        { sv: "Ett litet hopfällbart tält bildar en triangel där den översta delen har sidolängden {top} dm och basen {smallBase} dm. När tältet fälls ut helt blir hela sidolängden {totSide} dm. Hur bred blir tältets bas på marken?", en: "A small folding tent forms a triangle where the top part has a side length of {top} dm and a base of {smallBase} dm. When fully unfolded, the total side length is {totSide} dm. How wide will the tent base be on the ground?" },
        { sv: "En triangelformad logga har en inre del med sidolängden {top} mm och basbredden {smallBase} mm. Hela loggans yttre kant bildar en likformig triangel med sidolängden {totSide} mm. Beräkna den yttre basen.", en: "A triangular logo has an inner part with a side length of {top} mm and a base width of {smallBase} mm. The entire outer border forms a similar triangle with a side length of {totSide} mm. Calculate the outer base." },
        { sv: "En liten triangelformad flagga har sidolängden {top} cm och basen {smallBase} cm. En stor fana görs likformig med flaggan men med den totala sidolängden {totSide} cm. Hur bred blir den stora fanans bas?", en: "A small triangular flag has a side length of {top} cm and a base of {smallBase} cm. A large banner is made similar to the flag but with a total side length of {totSide} cm. How wide will the large banner's base be?" },
        { sv: "En liten triangelformad ram i en leksak har måtten {top} cm på sidan och {smallBase} cm på basen. Den yttre ramen bildar en likformig triangel med sidolängden {totSide} cm. Beräkna den yttre ramens bas.", en: "A small triangular frame in a toy measures {top} cm on the side and {smallBase} cm at the base. The outer frame forms a similar triangle with a side length of {totSide} cm. Calculate the outer frame's base." },
        { sv: "En liten modell av en pyramid har sidolängden {top} mm och basen {smallBase} mm. Den riktiga pyramiden är byggd likformigt så att hela sidolängden blir {totSide} cm. Vad blir den riktiga pyramidens bas?", en: "A small model of a pyramid has a side length of {top} mm and a base of {smallBase} mm. The real pyramid is built similarly so the total side length is {totSide} cm. What will the real pyramid's base be?" },
        { sv: "En liten triangel på en trälåda har måtten {top} cm på sidan och {smallBase} cm i basen. En stor likformig triangel ritas på en vägg med måttet {totSide} cm på sidan. Bestäm triangelns bas på väggen.", en: "A small triangle on a wooden box measures {top} cm on the side and {smallBase} cm at the base. A large similar triangle is drawn on a wall with a side measure of {totSide} cm. Determine the triangle's base on the wall." },
        { sv: "Ett litet mönster på ett staket har en inre bit med sidolängden {top} dm och en bas på {smallBase} dm. Den yttre ramen runt mönstret bildar en likformig triangel med en total längd på {totSide} dm. Hur bred blir den yttre basen?", en: "A small pattern on a fence has an inner piece with a side length of {top} dm and a base of {smallBase} dm. The outer frame around the pattern forms a similar triangle with a total length of {totSide} dm. How wide will the outer base be?" },
        { sv: "En skugga bildar en liten triangel på marken med längden {top} m och basen {smallBase} m. En större skugga bredvid bildar en stor likformig triangel med den totala längden {totSide} m. Bestäm bredden på den stora skuggans bas.", en: "A shadow forms a small triangle on the ground with a length of {top} m and a base of {smallBase} m. A larger shadow next to it forms a large similar triangle with a total length of {totSide} m. Determine the width of the large shadow's base." }
    ],

    // =========================================================================
    // 📐 5. TRANSVERSAL: PARTIAL EXTENSION VIEW (15 Stories)
    //    Parameters: {top}, {extra}, {smallBase} -> Find bigBase ('x')
    // =========================================================================
    transversal_extension: [
        { sv: "En liten pinne som sticker upp {smallBase} dm ur marken kastar en skugga på {top} dm. En bit bakom står ett träd vars skugga slutar på exakt samma ställe. Avståndet längs marken från pinnen till trädet är {extra} dm. Hur högt är trädet?", en: "A small stick standing {smallBase} dm out of the ground casts a shadow of {top} dm. A tree stands behind it, and its shadow ends at the exact same spot. The distance along the ground from the stick to the tree is {extra} dm. How tall is the tree?" },
        { sv: "En kompis som är {smallBase} cm lång kastar en skugga på {top} cm på marken under en gatulykta. Det uppmätta avståndet på marken från kompisen till lyktstolpen är {extra} cm. Räkna ut hur högt upp lampan sitter.", en: "A friend who is {smallBase} cm tall casts a shadow of {top} cm on the ground under a streetlight. The measured distance on the ground from the friend to the lamppost is {extra} cm. Calculate how high up the lamp is." },
        { sv: "En liten provramp går upp {smallBase} cm över ett markavstånd på {top} cm. Den stora riktiga rampen byggs i exakt samma lutning men sträcker sig ytterligare {extra} cm längre längs marken. Bestäm den stora rampens totala höjd.", en: "A small test ramp rises {smallBase} cm over a ground distance of {top} cm. The large real ramp is built with the exact same slope but extends an additional {extra} cm along the ground. Determine the large ramp's total height." },
        { sv: "Ett litet staket som är {smallBase} dm högt kastar en skugga på {top} dm. En bit bakom staket står en stolpe vars skugga slutar på samma ställe som staketets skugga. Avståndet från staketet till stolpen är {extra} dm. Hur hög är stolpen?", en: "A small fence that is {smallBase} dm high casts a shadow of {top} dm. Behind the fence stands a pole whose shadow ends at the same spot as the fence's shadow. The distance from the fence to the pole is {extra} dm. How tall is the pole?" },
        { sv: "En linjal på {smallBase} cm står rakt upp och kastar en {top} cm lång skugga på marken. En bit bort står en husvägg vars skugga slutar på samma ställe. Avståndet på marken från linjalen till husväggen är {extra} cm. Räkna ut husets höjd.", en: "A ruler of {smallBase} cm stands straight up and casts a {top} cm long shadow on the ground. A bit further away is a house wall whose shadow ends at the same spot. The distance on the ground from the ruler to the house wall is {extra} cm. Calculate the house's height." },
        { sv: "Ett litet buskage som är {smallBase} m högt kastar en skugga på {top} m. En hög vägg står placerad så att dess skugga slutar exakt där buskens skugga slutar. Avståndet på marken mellan busken och väggen är {extra} m. Hur hög är väggen?", en: "A small bush that is {smallBase} m tall casts a shadow of {top} m. A high wall is positioned so that its shadow ends exactly where the bush's shadow ends. The distance on the ground between the bush and the wall is {extra} m. How tall is the wall?" },
        { sv: "En vertikal pinne på {smallBase} m kastar en {top} m lång skugga. En skorsten på ett hus bakom pinnen kastar en skugga som når till samma punkt. Avståndet på marken mellan pinnen och huset är {extra} m. Beräkna skorstenens höjd.", en: "A vertical stick of {smallBase} m casts a {top} m long shadow. A chimney on a house behind the stick casts a shadow reaching the same point. The distance on the ground between the stick and the house is {extra} m. Calculate the chimney's height." },
        { sv: "En kompis som är {smallBase} m lång står framför en liten lampa på golvet och kastar en skugga på en vägg. Avståndet från lampan till kompisen är {top} m, och det är {extra} m kvar fram till väggen. Hur hög blir skuggan på väggen?", en: "A friend who is {smallBase} m tall stands in front of a small light on the floor and casts a shadow on a wall. The distance from the light to the friend is {top} m, and there are {extra} m left to the wall. How tall will the shadow be on the wall?" },
        { sv: "Ett litet snett stöd till en cykelramp går upp {smallBase} mm på en marklängd på {top} mm. Hela den stora rampen byggs i samma vinkel men sträcker sig ytterligare {extra} mm längs marken. Beräkna hela rampens höjd.", en: "A small angled support for a bike ramp rises {smallBase} mm over a ground length of {top} mm. The whole large ramp is built at the same angle but extends an additional {extra} mm along the ground. Calculate the total height of the ramp." },
        { sv: "En liten mätsticka sticker upp {smallBase} cm över marken och kastar en skugga på {top} cm. Ett hus bakom stickan kastar en skugga till samma slutpunkt, och avståndet från stickan till huset är {extra} cm. Hur högt är huset?", en: "A small measuring stick stands {smallBase} cm out of the ground and casts a shadow of {top} cm. A house behind the stick casts a shadow to the same endpoint, and the distance from the stick to the house is {extra} cm. How high is the house?" },
        { sv: "En hög flaggstång kastar en lång skugga. En liten pinne på {smallBase} m placeras så att dess skugga slutar exakt där flaggstångens skugga slutar. Pinnens skugga är {top} m, och det är {extra} m mellan pinnen och flaggstången. Hur hög är flaggstången?", en: "A tall flagpole casts a long shadow. A small stick of {smallBase} m is placed so that its shadow ends exactly where the flagpole's shadow ends. The stick's shadow is {top} m, and it is {extra} m between the stick and the flagpole. How tall is the flagpole?" },
        { sv: "En liten leksaksramp höjer sig {smallBase} cm över en bas på {top} cm. Den riktiga skateboard-rampen byggs i samma lutning men sträcker sig ytterligare {extra} cm på marken. Bestäm den riktiga rampens totala höjd.", en: "A small toy ramp rises {smallBase} cm over a base of {top} cm. The real skateboard ramp is built with the same slope but extends an additional {extra} cm on the ground. Determine the real ramp's total height." },
        { sv: "Ett litet trästöd till ett brädspel är {smallBase} m högt och fäster {top} m ut på bordet. Ett mycket större likformigt stöd byggs till en möbel och sträcker sig ytterligare {extra} m ut på golvet. Beräkna det stora stödets totala höjd.", en: "A small wooden support for a board game is {smallBase} m high and attaches {top} m out on the table. A much larger similar support is built for furniture and extends an additional {extra} m out on the floor. Calculate the large support's total height." },
        { sv: "Två stegar lutar mot en vägg i samma lutning. Den lilla stegen når {smallBase} m upp på väggen och står {top} m ut på marken. Den stora stegen står placerad ytterligare {extra} m ut från väggen på marken. Hur högt upp på väggen når den stora stegen?", en: "Two ladders lean against a wall at the same slope. The short ladder reaches {smallBase} m up the wall and stands {top} m out on the ground. The large ladder is positioned an additional {extra} m out from the wall on the ground. How high up the wall does the large ladder reach?" },
        { sv: "En vertikal stolpe på {smallBase} m kastar en skugga på {top} m på skolgården. En stor byggnad bredvid kastar en skugga till samma slutpunkt, och avståndet på marken från stolpen till byggnadens vägg är {extra} m. Beräkna byggnadens höjd.", en: "A vertical pole of {smallBase} m casts a shadow of {top} m on the schoolyard. A large building next to it casts a shadow to the same endpoint, and the distance on the ground from the pole to the building's wall is {extra} m. Calculate the building's height." }
    ]
};